version: "3.9"
services:
  frontend_app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - REACT_APP_MAPS_KEY=$REACT_APP_MAPS_KEY
      - SERVER_URL=http://ec2-44-214-38-103.compute-1.amazonaws.com
    command: >
      sh -c "npm install &&
             npm start"
