version: "3.9"
services:
  frontend_app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
    - REACT_APP_MAPS_KEY=$REACT_APP_MAPS_KEY
    command: >
      sh -c "npm install &&
             npm start"
